#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
螃蟹账号平台商品数据分析脚本
分析时间: 2026-04-03
"""

import json
from datetime import datetime
from collections import Counter
import re

# 商品类型筛选栏选项
product_types = ["账号", "代练"]

# 从浏览器获取的112个商品数据
products = [
    {"platform":"QQ","price":10000,"title":"QQ，双字ID 似琦"},
    {"platform":"QQ","price":66,"title":"QQ，双字ID 黑暮"},
    {"platform":"QQ","price":6000,"title":"QQ，热门ID 哈萨维•诺亚"},
    {"platform":"QQ","price":8888,"title":"QQ，热门ID 卡缪·维丹"},
    {"platform":"QQ","price":588,"title":"QQ，双字ID 鲜血"},
    {"platform":"QQ","price":6666,"title":"QQ，热门ID 柯特罗巴吉纳"},
    {"platform":"微信","price":50000,"title":"微信，单字ID 孤"},
    {"platform":"微信","price":2000,"title":"微信，双字ID 𠃌𠃍"},
    {"platform":"QQ","price":2000,"title":"QQ，双字ID 𠃌夜"},
    {"platform":"QQ","price":999,"title":"QQ，双字ID 丞烨"},
    {"platform":"QQ","price":700,"title":"QQ，热门ID 叶承烨"},
    {"platform":"QQ","price":4000,"title":"QQ，双字ID 挽留"},
    {"platform":"QQ","price":999,"title":"QQ，双字ID 帝宏"},
    {"platform":"QQ","price":4000,"title":"QQ，双字ID ib"},
    {"platform":"QQ","price":10000,"title":"QQ，单字ID 年"},
    {"platform":"QQ","price":1999,"title":"QQ，双字ID 许配"},
    {"platform":"QQ","price":99,"title":"QQ，热门ID 悲傷劇情"},
    {"platform":"QQ","price":1000,"title":"QQ，双字ID 古灵"},
    {"platform":"微信","price":1500,"title":"微信，热门ID 古或今"},
    {"platform":"微信","price":100,"title":"微信，双字ID 杳儿"},
    {"platform":"QQ","price":128.8,"title":"QQ，热门ID 電影院"},
    {"platform":"QQ","price":200,"title":"QQ，单字ID 竬"},
    {"platform":"微信","price":100,"title":"微信，双字ID 沉杳"},
    {"platform":"QQ","price":118.8,"title":"QQ，热门ID 收銀員"},
    {"platform":"QQ","price":150,"title":"QQ，单字ID 䏀"},
    {"platform":"QQ","price":13140,"title":"QQ，单字ID 萝"},
    {"platform":"QQ","price":2000,"title":"QQ，单字ID 收"},
    {"platform":"QQ","price":128.8,"title":"QQ，热门ID 詩歌劇"},
    {"platform":"QQ","price":1200,"title":"QQ，双字ID 殿主"},
    {"platform":"微信","price":2000,"title":"微信，单字ID 匪"},
    {"platform":"QQ","price":1200,"title":"QQ，单字ID 刚"},
    {"platform":"QQ","price":50000,"title":"QQ，双字ID 青年"},
    {"platform":"微信","price":2500,"title":"微信，单字ID 常见单字没"},
    {"platform":"QQ","price":1888,"title":"QQ，双字ID 赌徒"},
    {"platform":"QQ","price":1888,"title":"QQ，双字ID 辣妹"},
    {"platform":"QQ","price":780,"title":"QQ，双字ID 身后"},
    {"platform":"微信","price":10000,"title":"微信，双字ID 单纯"},
    {"platform":"QQ","price":350,"title":"QQ，单字ID 梉"},
    {"platform":"QQ","price":3500,"title":"QQ，单字ID 告"},
    {"platform":"QQ","price":400,"title":"QQ，双字ID"},
    {"platform":"QQ","price":52000,"title":"QQ，双字ID 萝莉"},
    {"platform":"QQ","price":588,"title":"QQ，双字ID 汉人"},
    {"platform":"QQ","price":188,"title":"QQ，单字ID 佖"},
    {"platform":"微信","price":8888,"title":"微信，单字ID 从"},
    {"platform":"QQ","price":299,"title":"QQ，单字ID 韖"},
    {"platform":"QQ","price":120,"title":"QQ，单字ID g"},
    {"platform":"QQ","price":60,"title":"QQ，热门ID 黑魔神"},
    {"platform":"QQ","price":60,"title":"QQ，热门ID 吞天神"},
    {"platform":"QQ","price":60,"title":"QQ，热门ID 神魔天帝"},
    {"platform":"QQ","price":3000,"title":"QQ，英文ID wifey"},
    {"platform":"QQ","price":666,"title":"QQ，双字ID 蛇妇"},
    {"platform":"QQ","price":288,"title":"QQ，热门ID 黑袜肌肉精牛"},
    {"platform":"QQ","price":2000,"title":"QQ，双字ID 梁乡"},
    {"platform":"微信","price":100,"title":"微信，热门ID 悔命蛊"},
    {"platform":"QQ","price":120,"title":"QQ，热门ID 创造神"},
    {"platform":"QQ","price":120,"title":"QQ，单字ID 窖"},
    {"platform":"QQ","price":500,"title":"QQ，单字ID 뭘"},
    {"platform":"QQ","price":520,"title":"QQ，双字ID 粤星"},
    {"platform":"QQ","price":600,"title":"QQ，单字ID 窖"},
    {"platform":"QQ","price":4000,"title":"QQ，情侣ID 相守一生"},
    {"platform":"QQ","price":80,"title":"QQ，双字ID 噬恶"},
    {"platform":"QQ","price":4000,"title":"QQ，情侣ID 顾你一世"},
    {"platform":"QQ","price":230,"title":"QQ，双字ID"},
    {"platform":"QQ","price":10000,"title":"QQ，单字ID 戚"},
    {"platform":"QQ","price":5000,"title":"QQ，单字ID 捥"},
    {"platform":"QQ","price":580,"title":"QQ，双字ID 博识"},
    {"platform":"QQ","price":999,"title":"QQ，热门ID 帕里塔"},
    {"platform":"QQ","price":1500,"title":"QQ，热门ID 词晚秋"},
    {"platform":"微信","price":2000,"title":"微信，热门ID 魔法少女唯酱"},
    {"platform":"QQ","price":1500,"title":"QQ，双字ID 北墙"},
    {"platform":"QQ","price":999,"title":"QQ，热门ID 原告人蔡徐坤"},
    {"platform":"QQ","price":2000,"title":"QQ，热门ID 甄子丹"},
    {"platform":"QQ","price":999,"title":"QQ，热门ID 被告人蔡徐坤"},
    {"platform":"QQ","price":450,"title":"QQ，双字ID 多加"},
    {"platform":"QQ","price":60,"title":"QQ，双字ID 孑黎"},
    {"platform":"QQ","price":222,"title":"QQ，双字ID 可控"},
    {"platform":"QQ","price":1500,"title":"QQ，单字ID 槑"},
    {"platform":"QQ","price":1314,"title":"QQ，双字ID 认准"},
    {"platform":"微信","price":2666,"title":"微信，双字ID 敌军"},
    {"platform":"QQ","price":888,"title":"QQ，双字ID 闷气"},
    {"platform":"QQ","price":666,"title":"QQ，双字ID 萝莉声"},
    {"platform":"QQ","price":666,"title":"QQ，双字ID 送亲"},
    {"platform":"QQ","price":888,"title":"QQ，双字ID 勾住"},
    {"platform":"QQ","price":200,"title":"QQ，双字ID 荒懿"},
    {"platform":"微信","price":888,"title":"微信，单字ID 嗯"},
    {"platform":"QQ","price":10000,"title":"QQ，双字ID 左阳"},
    {"platform":"QQ","price":1000,"title":"QQ，单字ID 茧"},
    {"platform":"QQ","price":8888,"title":"QQ，热门ID 小天使"},
    {"platform":"微信","price":250000,"title":"微信，热门ID 林智宇"},
    {"platform":"QQ","price":588,"title":"QQ，双字ID 鼎宙"},
    {"platform":"QQ","price":666,"title":"QQ，双字ID"},
    {"platform":"QQ","price":888,"title":"QQ，双字ID 伤凌"},
    {"platform":"QQ","price":520,"title":"QQ，单字ID 凌"},
    {"platform":"QQ","price":50000,"title":"QQ，英文ID ⿹"},
    {"platform":"QQ","price":1800,"title":"QQ，热门ID 勿忘朵朵"},
    {"platform":"QQ","price":500,"title":"QQ，双字ID 儍萌"},
    {"platform":"QQ","price":300,"title":"QQ，双字ID 斩辰"},
    {"platform":"QQ","price":900,"title":"QQ，单字ID 