#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""保存盼之商品数据到JSON文件"""

import json

# 从浏览器提取的100条数据
data = [
    {"platform":"安卓QQ","price":999999,"title":"王者荣耀：世界火热招商中！！","views":None,"wants":1107},
    {"platform":"安卓QQ","price":888,"title":"极品ID:天赋哥，可带号出，诚心出可议价","views":5453,"wants":523},
    {"platform":"苹果QQ","price":999,"title":"ID衿","views":8285,"wants":813},
    {"platform":"","price":1288,"title":"22级t0账号（目前20级很难升，全服不超过1000个）我还在继续升级中，肝到被人买为止，极品双字l","views":None,"wants":50},
    {"platform":"","price":888,"title":"单字id嗯，无空格无特殊符号。","views":None,"wants":64},
    {"platform":"","price":1234,"title":"内测充值500","views":None,"wants":105},
    {"platform":"","price":850,"title":"贵八一荣耀典藏","views":None,"wants":97},
    {"platform":"","price":999,"title":"美琴","views":None,"wants":92},
    {"platform":"","price":1111,"title":"内测返利500","views":None,"wants":141},
    {"platform":"","price":888,"title":"王者荣耀进度号","views":None,"wants":120},
    {"platform":"苹果QQ","price":603,"title":"渣","views":1993,"wants":184},
    {"platform":"","price":899,"title":"20级t0账号（目前20级很难升，全服不超过1000个）我还在继续升级中，肝到被人买为止，极品双字l","views":None,"wants":45},
    {"platform":"安卓QQ","price":630,"title":"id便宜","views":3991,"wants":399},
    {"platform":"苹果QQ","price":888,"title":"双字ID超御","views":3513,"wants":327},
    {"platform":"安卓QQ","price":850,"title":"热门ID四字:永雏塔霏","views":2532,"wants":240},
    {"platform":"安卓QQ","price":810,"title":"id0氪","views":1977,"wants":190},
    {"platform":"安卓QQ","price":999,"title":"单字id敌","views":2044,"wants":195},
    {"platform":"安卓QQ","price":1200,"title":"王者荣耀世界双字id","views":1750,"wants":171},
    {"platform":"","price":999,"title":"荣耀战令已开通-开服5位数字ID2开头，极品3字ABB女生ID，可二次实名，人脸可改，全剧情+全收集","views":None,"wants":10},
    {"platform":"安卓QQ","price":999,"title":"单字id峻","views":1550,"wants":145},
    {"platform":"安卓QQ","price":721,"title":"id双胞胎","views":978,"wants":89},
    {"platform":"安卓QQ","price":788,"title":"极品单子🆔媤，纯单字无符号放心.适合女用，偏旁带思，适合本命带思的帅哥美女。白菜价，标价非最终卖价","views":1870,"wants":168},
    {"platform":"安卓QQ","price":750,"title":"达观id出售","views":1420,"wants":132},
    {"platform":"苹果QQ","price":888,"title":"耻辱","views":1227,"wants":112},
    {"platform":"安卓QQ","price":999,"title":"极品单子🆔剪，纯单字无符号放心拍。白菜价，标价非最终卖价，喜欢可详谈。","views":1953,"wants":178},
    {"platform":"安卓QQ","price":1200,"title":"顶级ID宇宙，要的来","views":410,"wants":35},
    {"platform":"苹果QQ","price":888,"title":"极品双字🆔：感叹","views":788,"wants":37},
    {"platform":"安卓微信","price":788,"title":"极品单子🆔馁，纯单字无符号放心拍。白菜价，标价非最终卖价，喜欢可详谈。不带号只出🆔","views":2704,"wants":257},
    {"platform":"苹果QQ","price":888,"title":"双字🆔：好宅","views":1567,"wants":115},
    {"platform":"安卓QQ","price":900,"title":"极品帅哥id:偏爱纵容，喜欢可谈，有搭配情侣id女号:性格娇纵","views":1894,"wants":174},
    {"platform":"苹果QQ","price":1000,"title":"Id：愿中国永无难，喜欢的可以聊","views":1179,"wants":106},
    {"platform":"苹果QQ","price":888,"title":"出极品单子id实","views":1186,"wants":119},
    {"platform":"安卓微信","price":799,"title":"id:笨笨少女，可爱妹妹必备斩男id，诚心可谈，价格实惠","views":1509,"wants":127},
    {"platform":"苹果QQ","price":888,"title":"极品双字id色骨","views":1325,"wants":131},
    {"platform":"安卓QQ","price":888,"title":"极品昵称，吾乃吴彦祖","views":843,"wants":83},
    {"platform":"安卓QQ","price":900,"title":"极品美女id:性格娇纵，喜欢可谈，有搭配情侣id男号:偏爱纵容，一起购买可更优惠","views":1343,"wants":112},
    {"platform":"安卓QQ","price":1288,"title":"极品昵称，刘亦菲lyf","views":999,"wants":101},
    {"platform":"苹果QQ","price":850,"title":"双字词组🆔推辞","views":1480,"wants":117},
    {"platform":"安卓QQ","price":888,"title":"极品昵称，吾乃彭于晏","views":978,"wants":94},
    {"platform":"苹果QQ","price":888,"title":"正版id婚戒","views":772,"wants":73},
    {"platform":"安卓QQ","price":1200,"title":"极品双子ID：绘织","views":892,"wants":86},
    {"platform":"苹果QQ","price":999,"title":"极品单字🆔瞻","views":1262,"wants":120},
    {"platform":"安卓QQ","price":888,"title":"情侣id,乖乖宠，还有一个号叫宠乖乖","views":773,"wants":64},
    {"platform":"安卓QQ","price":980,"title":"极品双字ID：怯糖","views":754,"wants":70},
    {"platform":"苹果QQ","price":720,"title":"极品二字id：玉佩","views":1540,"wants":141},
    {"platform":"安卓QQ","price":888,"title":"情侣id，宠乖乖，另一个号乖乖宠","views":682,"wants":57},
    {"platform":"","price":8888,"title":"单字id光，带号出","views":None,"wants":25},
    {"platform":"","price":666,"title":"单字ld，剫","views":None,"wants":5},
    {"platform":"安卓QQ","price":288,"title":"五位数极品uid49777","views":None,"wants":28},
    {"platform":"","price":100,"title":"剧情已过","views":None,"wants":8},
    {"platform":"","price":599,"title":"极品id赵怀真","views":None,"wants":18},
    {"platform":"","price":1500,"title":"荣耀装等20，波流3级，元流20级，女主，收藏度20，第一天满肝度，已购买战令","views":None,"wants":13},
    {"platform":"","price":6666,"title":"单子ID","views":None,"wants":10},
    {"platform":"","price":2982,"title":"单字id:年","views":None,"wants":8},
    {"platform":"","price":130,"title":"15级有68战令","views":None,"wants":16},
    {"platform":"","price":126,"title":"王者世界战令17级第四章已完成进度号，伽罗已拿。","views":None,"wants":23},
    {"platform":"","price":100,"title":"成品号","views":None,"wants":11},
    {"platform":"","price":666,"title":"常用双字名（求语）+6位数字，练度来到第一天T0位置，第一天主线已经做到极限，地图全开，AA+手慢无","views":None,"wants":13},
    {"platform":"","price":5000,"title":"王者荣耀世界","views":None,"wants":16},
    {"platform":"","price":160,"title":"主线推至11级，5位uid","views":None,"wants":15},
    {"platform":"","price":1888,"title":"🆔恋爱","views":None,"wants":12},
    {"platform":"","price":111,"title":"6级账号","views":None,"wants":14},
    {"platform":"","price":500,"title":"王者荣耀世界极品单子ID,第一天肝度拉满","views":None,"wants":74},
    {"platform":"","price":520,"title":"双字ID崽梨","views":None,"wants":10},
    {"platform":"","price":666,"title":"出号全新","views":None,"wants":10},
    {"platform":"","price":123,"title":"6级账号","views":None,"wants":10},
    {"platform":"","price":3333,"title":"内测充值2000","views":None,"wants":31},
    {"platform":"","price":200,"title":"13级","views":None,"wants":11},
    {"platform":"","price":499,"title":"开服账号","views":None,"wants":14},
    {"platform":"","price":666,"title":"单字id屍，无空白编号87523可带号出","views":None,"wants":11},
    {"platform":"","price":300,"title":"地图传送点位全部已开，9级女角色","views":None,"wants":13},
    {"platform":"","price":4000,"title":"差六千多v10，小漂亮女号，大乔全皮差星元瑶差一个，不用太在意我的报价大胆砍","views":None,"wants":12},
    {"platform":"","price":599,"title":"已过新手任务","views":None,"wants":15},
    {"platform":"","price":73,"title":"昵称:多亏你了，可小刀","views":None,"wants":13},
    {"platform":"安卓QQ","price":6888,"title":"极品二字ID：奶凶，可带号出","views":1613,"wants":166},
    {"platform":"","price":239,"title":"刚开的豪华通行证，现在13级","views":None,"wants":51},
    {"platform":"","price":158,"title":"极品昵称:别想她，编号:202730特别好记","views":None,"wants":12},
    {"platform":"","price":188,"title":"id桃枳雾 已过新手任务上手直接体验","views":None,"wants":14},
    {"platform":"","price":1500,"title":"游戏ID阿坝州","views":None,"wants":12},
    {"platform":"安卓QQ","price":188,"title":"极品二字ID：定期，带号诚心出，可议价","views":2730,"wants":260},
    {"platform":"","price":188,"title":"王者荣耀世界2字id成品号","views":None,"wants":20},
    {"platform":"","price":333,"title":"已过新手任务","views":None,"wants":16},
    {"platform":"","price":2000,"title":"晴海雾纱","views":None,"wants":67},
    {"platform":"安卓QQ","price":200,"title":"双字id：冷曜","views":407,"wants":32},
    {"platform":"安卓微信","price":110,"title":"双字🆔漱口，无空白符号，可自己上号改","views":None,"wants":27},
    {"platform":"安卓QQ","price":100,"title":"3字🆔蕾欧娜，无空白符号，可自己上号改","views":None,"wants":34},
    {"platform":"","price":50,"title":"三无新Q预约账号。","views":None,"wants":32},
    {"platform":"安卓QQ","price":1940,"title":"退游","views":None,"wants":130},
    {"platform":"安卓QQ","price":99999,"title":"11","views":None,"wants":27},
    {"platform":"安卓QQ","price":350,"title":"极品网红id","views":None,"wants":31},
    {"platform":"安卓QQ","price":659,"title":"已过新手动画，快速可玩","views":None,"wants":26},
    {"platform":"苹果QQ","price":399,"title":"id：咔嗒","views":259,"wants":23},
    {"platform":"安卓QQ","price":150,"title":"双字🆔拉丁，无空白符号，带Q出","views":None,"wants":26},
    {"platform":"安卓QQ","price":6595,"title":"返利号内测充值4260","views":444,"wants":58},
    {"platform":"苹果微信","price":399,"title":"id 心软酱","views":262,"wants":22},
    {"platform":"安卓QQ","price":100,"title":"双字🆔木炭，无空白符号，带Q出","views":None,"wants":30},
    {"platform":"安卓QQ","price":6666,"title":"内测充值4000","views":356,"wants":43},
    {"platform":"安卓QQ","price":5555,"title":"内测3500返利号","views":328,"wants":40},
    {"platform":"安卓QQ","price":150,"title":"双字🆔小兴，无空白符号，可自己上号改","views":None,"wants":26},
    {"platform":"安卓QQ","price":500,"title":"安详","views":187,"wants":19},
    {"platform":"安卓QQ","price":188,"title":"极品二字ID：估值，带号出，诚心出可议价","views":1842,"wants":177},
    {"platform":"安卓QQ","price":130,"title":"双字🆔锅盖，无空白符号，带Q出","views":None,"wants":21},
    {"platform":"","price":49999,"title":"极品id斩断，无空白字符","views":434,"wants":46},
    {"platform":"安卓QQ","price":688,"title":"极品ID：隔壁小王，号里还有一个王者皮肤号，诚心出可议价","views":1696,"wants":162}
]

# 保存为JSON文件
output_file = '/Users/jiewen/.real/users/user-777da3823a68e71779b041c8e7807df0/workspace/pzds_goods_data.json'
with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"✅ 成功保存 {len(data)} 条商品数据到 pzds_goods_data.json")
print(f"📁 文件路径: {output_file}")
